-- MySQL Script generated by MySQL Workbench
-- Sun Oct 15 14:16:59 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema simple_company
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema simple_company
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `simple_company` DEFAULT CHARACTER SET utf8 ;
USE `simple_company` ;

-- -----------------------------------------------------
-- Table `simple_company`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simple_company`.`Product` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `prodName` VARCHAR(45) NULL,
  `prodDescription` VARCHAR(45) NULL,
  `prodCategory` INT NULL,
  `prodUPC` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simple_company`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simple_company`.`Customer` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `gender` CHAR(1) NULL,
  `dob` DATE NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simple_company`.`Purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simple_company`.`Purchase` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `productID` BIGINT NULL,
  `customerID` BIGINT NULL,
  `purchaseDate` DATE NULL,
  `purchaseAmount` DECIMAL(64,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_prodID_idx` (`productID` ASC),
  INDEX `fk_custID_idx` (`customerID` ASC),
  CONSTRAINT `fk_prodID`
    FOREIGN KEY (`productID`)
    REFERENCES `simple_company`.`Product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_custID`
    FOREIGN KEY (`customerID`)
    REFERENCES `simple_company`.`Customer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simple_company`.`CreditCard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simple_company`.`CreditCard` (
  `name` VARCHAR(45) NULL,
  `ccNumber` VARCHAR(45) NULL,
  `expDate` VARCHAR(45) NULL,
  `securityCode` VARCHAR(45) NULL,
  `ownerID` BIGINT NOT NULL,
  PRIMARY KEY (`ownerID`),
  CONSTRAINT `fk_ownerID`
    FOREIGN KEY (`ownerID`)
    REFERENCES `simple_company`.`Customer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simple_company`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simple_company`.`Address` (
  `address1` VARCHAR(45) NULL,
  `address2` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `zipcode` VARCHAR(45) NULL,
  `ownerID` BIGINT NOT NULL,
  PRIMARY KEY (`ownerID`),
  CONSTRAINT `fk_owner`
    FOREIGN KEY (`ownerID`)
    REFERENCES `simple_company`.`Customer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
